apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  IPv6: false
  debug: true
  imagePullSecrets: []
  imageRegistry: ""
  namespace: trident
  nodePrep:
  - iscsi
  silenceAutosupport: false
status: {}
